config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/new'

  resources :challenges
  root 'welcome#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  get '/entries/new', to: 'activity_entries#new', as: 'new_entry'
  resources :activity_entries, only: [:create, :edit, :destroy]

  get '/dashboard', to: 'dashboard#new', as: "dashboard"

  get 'signup/admin', to: 'users#new_admin', as: 'admin_signup'
  post 'signup/admin', to: 'users#create'

  resources :users_challenges, only: [:new, :create]

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  post '/avatar', to: 'users#avatar', as: 'avatar'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :activity_entries
  has_many :users_challenges
  has_many :challenges, through: :users_challenges

  validates :username, uniqueness: {message: "has already been taken!"}
  validates :username, :first_name, :last_name, :city, :password, :age, :weight, :email, presence: true
  validates :email, uniqueness: true
  validates :email, email_format: { message: "isn't properly formatted." }
  validates :age, numericality: {greater_than_or_equal_to: 17}

  def weight_class
    if self.weight <= 130
      "cph_130"
    elsif self.weight <=155
      "cph_155"
    elsif self.weight <= 180
      "cph_180"
    else
      "cph_205"
    end
  end

  def find_calories_by_days_ago(days_ago)
    @date_from = (Time.zone.now - days_ago.day).beginning_of_day
    @date_to = (Time.zone.now - (days_ago - 1).day).beginning_of_day
    self.activity_entries.where("created_at BETWEEN ? AND ?", @date_from, @date_to).sum(:calories_burned)
  end

  def find_calories_by_challenge(start_date, end_date)
    self.activity_entries.where("created_at BETWEEN ? AND ?", (start_date - 5.hours), (end_date- 5.hours)).sum(:calories_burned)
  end

  def self.last_week
     User.where('created_at BETWEEN ? AND ?', (Time.zone.now - 7),(Time.zone.now + 1))
  end

  def self.new_ytd(year)
    User.where('created_at BETWEEN ? AND ?', "#{year}-01-01", "#{year}-12-31")
  end

  def self.new_today
    User.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def self.active_users
    User.where(@user.activity_entries.where("created_at BETWEEN ? AND ?", Time.zone.now, Time.zone.now - 7))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :new_admin]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error]= @user.errors.full_messages.first if @user.errors.any?
      render 'new'
    end
  end

  def show
    @user = find_user
    @chart = Fusioncharts::Chart.new({
      width: "600",
      height: "400",
      type: "column3d",
      renderAt: "chartContainer",
      dataSource: {
        "chart": {
            "caption": "Weekly Calories Burned (Last 7 Days)",
            "xAxisName": "Days",
            "yAxisName": "Calories Burned",
            "paletteColors": "#0075c2",
            "bgColor": "#ffffff",
            "borderAlpha": "20",
            "plotBorderAlpha": "10",
            "placevaluesInside": "1",
            "rotatevalues": "1",
            "valueFontColor": "#ffffff",
            "showXAxisLine": "1",
            "xAxisLineColor": "#999999",
            "divlineColor": "#999999",
            "divLineDashed": "1",
            "showAlternateHGridColor": "0",
        },
        "data": [
            {
                "label": "7 Days Ago",
                "value": @user.find_calories_by_days_ago(7)
            },
            {
                "label": "6 Days Ago",
                "value": @user.find_calories_by_days_ago(6)
            },
            {
                "label": "5 Days Ago",
                "value": @user.find_calories_by_days_ago(5)
            },
            {
                "label": "4 Days Ago",
                "value": @user.find_calories_by_days_ago(4)
            },
            {
                "label": "3 Days Ago",
                "value": @user.find_calories_by_days_ago(3)
            },
            {
                "label": "2 Days Ago",
                "value": @user.find_calories_by_days_ago(2)
            },
            {
                "label": "Yesterday",
                "value": @user.find_calories_by_days_ago(1)
            },
            {
                "label": "Today",
                "value": @user.activity_entries.where("created_at >= ?", Time.zone.now.beginning_of_day).sum(:calories_burned)
            }
          ]
        }
      })
    unless session[:user_id] == @user.id
      flash[:error] = "Mind ya business!"
      redirect_to user_path(session[:user_id])
    end
  end

  def edit
    @user = find_user
  end

  def update
    @user = find_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    find_user.destroy
    redirect_to root_path
  end

  # Admin actions

  def new_admin
    @user = User.new
  end

  # Avatar actions

  def avatar
    @user = User.find(params[:user_id])
    @user.update(avatar: params[:avatar_id])
  end

  private

    def find_user
      User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :username,
        :first_name,
        :last_name,
        :city,
        :password,
        :password_confirmation,
        :age,
        :weight,
        :admin,
        :email
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<%= form_for @user do |f| %>

  <%= f.label :username %><br>
  <%= f.text_field :username %><br>

  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>

  <%= f.label :city %><br>
  <%= f.text_field :city %><br>

  <%= f.label :age %><br>
  <%= f.number_field :age %><br>

  <%= f.label :weight %><br>
  <%= f.number_field :weight %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label 'Confirm your password: ' %><br>
  <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit %>

<% end %>

app/views/users/edit.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.erb
<h3 style="margin-left: 211px;">User Sign-up Analytics</h3>
<div id="chartContainer"><%= @chart.render() %></div>

app/views/users/new.erb
<h1>New User</h1>
<%= render 'form' %>

app/views/users/new_admin.erb
<h1>New User</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %><br>
  <%= f.text_field :username %><br>

  <%= f.label :email %><br>
  <%= f.text_field :email %><br>

  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>

  <%= f.label :city %><br>
  <%= f.text_field :city %><br>

  <%= f.label :age %><br>
  <%= f.number_field :age %><br>

  <%= f.label :weight %><br>
  <%= f.number_field :weight %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label 'Confirm your password: ' %><br>
  <%= f.password_field :password_confirmation %><br>
  <br>

  <%= f.label 'Admin ' %><br>
  <%= f.radio_button :admin, true, :value => true%>
  <br>

  <%= f.submit %>

<% end %>

app/views/users/show.erb
<div id="top-wrapper">
  <div class="avatar-container">
    <% if @user.avatar == nil  %>
      <% r = rand(11) %>
      <%= image_tag "avatars/#{r}.png", class: 'avatar', data: r %>
      <button id="ava">Save avatar!</button>
    <% else %>
      <%= image_tag "avatars/#{@user.avatar}.png", class: 'avatar', data: @user.avatar %>
    <% end %>    
  </div>

  <div id="profile-block">
    City: <%= @user.city %><br>
    Age: <%= @user.age %><br>
    Weight: <%= @user.weight %><br>
    <br>
    <%= link_to 'Add an activity', new_entry_path %><br>
    <%= link_to 'Enter a challenge', challenges_path %><br>
    <%= link_to 'Edit profile', edit_user_path(@user) %><br>
  </div>

  <div id="chartContainer" class="user-chart">
    <%= @chart.render() %>
  </div>
</div>

<div id="user-wrapper">
  <div id="history">
    <h2>Exercise History</h2>
    <table id="user-history" class="user_timeline table table-hover">
      <thead>
        <th style="text-align: left;">Activity</th>
        <th style="text-align: right;">Calories Burned</th>
        <th style="text-align: right;">Workout Date</th>
        <th style="text-align: right;">Delete?</th>
      </thead>
      <tbody>
      <% @user.activity_entries.reverse.each do |act| %>
      <tr>
        <td style="text-align: left;"><%= act.name %></td>
        <td style="text-align: right;"><%= act.calories_burned %></td>
        <td style="text-align: right;"><%= act.created_at.strftime("%m/%d/%Y") %></td>
        <td style="text-align: right;">
          <%= link_to( ("<i class='fa fa-times' data-method='delete' style='color: #b51111' aria-hidden='true'></i>").html_safe, activity_entry_url(act), method: :delete ) %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="challenges">
    <h2>Active Challenges</h2>
    <table class="user_challenges table table-hover">
      <thead>
        <th style="text-align: left;">Name</th>
        <th style="text-align: right;">Start Date</th>
        <th style="text-align: right;">End Date</th>
      </thead>
      <tbody>
      <% @user.challenges.reverse.each do |challenge| %>
      <tr>
        <td style="text-align: left;"><%= link_to(challenge.name, challenge_path(challenge)) %></td>
        <td style="text-align: right;"><%= challenge.start_date.strftime("%m/%d/%Y") %></td>
        <td style="text-align: right;"><%= challenge.end_date.strftime("%m/%d/%Y") %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>