config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/new'

  resources :challenges
  root 'welcome#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  get '/entries/new', to: 'activity_entries#new', as: 'new_entry'
  resources :activity_entries, only: [:create, :edit, :destroy]

  get '/dashboard', to: 'dashboard#new', as: "dashboard"

  get 'signup/admin', to: 'users#new_admin', as: 'admin_signup'
  post 'signup/admin', to: 'users#create'

  resources :users_challenges, only: [:new, :create]

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  post '/avatar', to: 'users#avatar', as: 'avatar'

end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :users_challenges
  has_many :users, through: :users_challenges

  #should validate for name, start and end time;
  #only users who are logged in can create a challenge
  
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :require_login

  def index
    @challenges = Challenge.all
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)
    if @challenge.save
      redirect_to challenge_path(@challenge)
    else
      render :new
    end
  end

  def show
    @challenge = current_challenge
  end

  def edit
    #this should only be a feature for the person who created this challenge
    @challenge = current_challenge
  end

  def update
    @challenge = current_challenge
    if @challenge.update(challenge_params)
      redirect_to challenge_path(@challenge)
    else
      render :edit
    end
  end

  def destroy
    #this should only be a feature for the person who created this challenge
    @challenge = current_challenge
    @challenge.destroy
    redirect_to challenges_path
  end

private

  def current_challenge
    Challenge.find(params[:id])
  end

  def challenge_params
    params.require(:challenge).permit(:name,:rules, :start_date, :end_date)
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.erb
<%= form_for @challenge do |f| %>
<%= f.label "Challenge Name" %><br>
<%= f.text_field :name %><br>
<%= f.label :rules %><br>
<%= f.text_area :rules %><br>
<%= f.label "Challenge start date and time" %><br>
<%= f.datetime_field :start_date %><br>
<%= f.label "Challenge end date and time" %><br>
<%= f.datetime_field :end_date%><br><br>
<%= f.submit %>
<% end  %>

app/views/challenges/edit.erb
<h1>Edit your challenge (only)</h1>
<%= render 'edit' %>

app/views/challenges/index.erb
<h1>Challenge yourself!</h1>
<br>
<br>
<%= link_to "Create", new_challenge_path, class: 'btn btn-success new_c_btn' %>
<br>
<br>
<br>
<br>
<table class="table table-hover" style="width: 800px; position: relative; bottom: 100px;">
  <thead>
    <th style="text-align: left;">Active Challenges </th>
    <th style="text-align: right;">Start Date</th>
    <th style="text-align: right;">End Date</th>
  </thead>
  <tbody>
    <% @challenges.each do |challenge| %>
    <% if challenge.end_date > (Date.today) %>
      <tr>
        <td style="text-align: left;"><%= link_to challenge.name, challenge_path(challenge) %></td>
        <td style="text-align: right;"><%= challenge.start_date.strftime("%m/%d/%Y") %></td>
        <td style="text-align: right;"><%= challenge.end_date.strftime("%m/%d/%Y") %></td>
      </tr>
      <br>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/challenges/new.erb
<h1>Create a new challenge (and invite your friends?)</h1>
<%= render 'form' %>

app/views/challenges/show.erb
<h2> Challenge: <%= @challenge.name %></h2>

<h3>The Rules:</h3>
<p style="font-size: 18px;"><%= @challenge.rules %></p>

<div style="display: inline-block;
    background: #eeeeee;
    border-radius: 9px;
    padding: 14px 15px 6px 19px;
    margin-top: 18px;
    margin-bottom: 10px;">
  <p><span style="font-weight: 700">Start Date:</span> <%= @challenge.start_date.strftime("%m/%d/%Y") %></p>
  <p><span style="font-weight: 700">End Date:</span> <%= @challenge.end_date.strftime("%m/%d/%Y") %></p>
</div>

<h3>The awesome participants:</h3>
<table id="challenge-people" class="table table-hover">
  <thead>
    <th style="text-align: left;">Contestant</th>
    <th style="text-align: right;">Calories Burned So Far</th>
  </thead>
  <tbody>
  <% @challenge.users.each do |user| %>
  <tr>

    <td style="text-align: left;"><%= user.first_name %> <%= user.last_name %> (<%= user.username %>)</td>

    <td style="text-align: right;"><%= user.find_calories_by_challenge(@challenge.start_date) %></td>
    
  </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= form_tag users_challenges_path do  %>
  <%= hidden_field_tag "challenge_id", @challenge.id %>
  <%= submit_tag "Enter this challenge" %>
<% end %>
<br>
<br>