config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/new'

  resources :challenges
  root 'welcome#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  get '/entries/new', to: 'activity_entries#new', as: 'new_entry'
  resources :activity_entries, only: [:create, :edit, :destroy]

  get '/dashboard', to: 'dashboard#new', as: "dashboard"

  get 'signup/admin', to: 'users#new_admin', as: 'admin_signup'
  post 'signup/admin', to: 'users#create'

  resources :users_challenges, only: [:new, :create]

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  post '/avatar', to: 'users#avatar', as: 'avatar'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iWorkout</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
    </head>
    <body>
      <!--  navbar -->
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="<%= root_url %>"/>iWorkout</a>
          </div>

          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <% if current_user %>
                <li><%= link_to "Hello, #{current_user.first_name}!", user_path(current_user) %></li>
                <% if !!current_user.admin %>
                <li><%= link_to "Admin Dashboard", dashboard_path %></li>
                <% end %>
                <li><%= link_to "Challenges", challenges_path %></li>
                <li><%= link_to "Log Out", logout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign Up", signup_path %></li>
                <li><%= link_to "Log In", login_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

    <div id="wrapper">

      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>